-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 08:42:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicio 3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ejercicio 3` ;

-- -----------------------------------------------------
-- Schema Ejercicio 3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicio 3` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicio 3` ;

-- -----------------------------------------------------
-- Table `Ejercicio 3`.`Datos_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio 3`.`Datos_Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio 3`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio 3`.`Cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Reserva_Cliente` INT NOT NULL,
  `Validacion_Cliente` VARCHAR(45) NULL,
  `Datos_Cliente_id` INT NOT NULL,
  PRIMARY KEY (`id_Cliente`, `Datos_Cliente_id`),
  CONSTRAINT `fk_Cliente_Datos_Cliente1`
    FOREIGN KEY (`Datos_Cliente_id`)
    REFERENCES `Ejercicio 3`.`Datos_Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Datos_Cliente1_idx` ON `Ejercicio 3`.`Cliente` (`Datos_Cliente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ejercicio 3`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio 3`.`Reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Numero_identificacion` INT NOT NULL,
  `Fecha_Inicio` DATETIME NOT NULL,
  `Fecha_Final` DATETIME NOT NULL,
  `Precio_Total` INT NOT NULL,
  `Litros_Combustible` INT NOT NULL,
  `Cliente_id_Cliente` INT NOT NULL,
  PRIMARY KEY (`id`, `Cliente_id_Cliente`),
  CONSTRAINT `fk_Reserva_Cliente`
    FOREIGN KEY (`Cliente_id_Cliente`)
    REFERENCES `Ejercicio 3`.`Cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Reserva_Cliente_idx` ON `Ejercicio 3`.`Reserva` (`Cliente_id_Cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ejercicio 3`.`COCHE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio 3`.`COCHE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Precio_Hora` INT NOT NULL,
  `Cliente_id_Cliente` INT NOT NULL,
  `Cliente_Datos_Cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Cliente_id_Cliente`, `Cliente_Datos_Cliente_id`),
  CONSTRAINT `fk_COCHE_Cliente1`
    FOREIGN KEY (`Cliente_id_Cliente` , `Cliente_Datos_Cliente_id`)
    REFERENCES `Ejercicio 3`.`Cliente` (`id_Cliente` , `Datos_Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_COCHE_Cliente1_idx` ON `Ejercicio 3`.`COCHE` (`Cliente_id_Cliente` ASC, `Cliente_Datos_Cliente_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
